# Generated by Django 5.1.7 on 2025-03-16 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ed_platform', '0002_alter_lessonmodel_video_url'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(verbose_name='дата оплаты')),
                ('cost', models.PositiveIntegerField(verbose_name='стоимость')),
                ('payment_type', models.CharField(choices=[('Наличные', 'Наличные'), ('Перевод', 'Перевод')], verbose_name='способ оплаты')),
                ('paid_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ed_platform.coursemodel', verbose_name='оплаченный курс')),
                ('paid_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ed_platform.lessonmodel', verbose_name='оплаченный урок')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='студент')),
            ],
            options={
                'verbose_name': 'оплата',
                'verbose_name_plural': 'оплата',
            },
        ),
    ]
