# Generated by Django 5.1.7 on 2025-03-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_paymentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='payment_date',
            field=models.DateField(auto_now_add=True, verbose_name='дата оплаты'),
        ),
    ]
