# Generated by Django 5.1.7 on 2025-03-17 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ed_platform', '0003_alter_lessonmodel_course'),
        ('users', '0005_alter_paymentmodel_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='paid_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paid_course', to='ed_platform.coursemodel', verbose_name='оплаченный курс'),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='paid_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paid_lesson', to='ed_platform.lessonmodel', verbose_name='оплаченный урок'),
        ),
    ]
