# Generated by Django 5.1.7 on 2025-03-18 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_paymentmodel_paid_course_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentmodel",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student",
                to=settings.AUTH_USER_MODEL,
                verbose_name="студент",
            ),
        ),
    ]
