# Generated by Django 5.1.7 on 2025-04-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_paymentmodel_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentmodel",
            name="payment_link",
            field=models.URLField(
                blank=True, null=True, verbose_name="ссылка на платеж"
            ),
        ),
        migrations.AddField(
            model_name="paymentmodel",
            name="session_id",
            field=models.CharField(
                blank=True, max_length=400, null=True, verbose_name="id сессии"
            ),
        ),
    ]
