# Generated by Django 5.1.7 on 2025-04-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_paymentmodel_payment_link_paymentmodel_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentmodel",
            name="payment_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="дата оплаты"),
        ),
        migrations.AlterField(
            model_name="paymentmodel",
            name="payment_type",
            field=models.CharField(
                blank=True,
                choices=[("Наличные", "Наличные"), ("Перевод", "Перевод")],
                null=True,
                verbose_name="способ оплаты",
            ),
        ),
    ]
