# Generated by Django 5.1.7 on 2025-04-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_paymentmodel_payment_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentmodel",
            name="payment_link",
            field=models.URLField(
                blank=True, max_length=400, null=True, verbose_name="ссылка на платеж"
            ),
        ),
    ]
