# Generated by Django 5.1.7 on 2025-03-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ed_platform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonmodel',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
