# Generated by Django 5.1.7 on 2025-03-22 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ed_platform", "0004_coursemodel_создатель_курса_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="coursemodel",
            old_name="Создатель курса",
            new_name="owner",
        ),
        migrations.RenameField(
            model_name="lessonmodel",
            old_name="Создатель урока",
            new_name="owner",
        ),
    ]
