# Generated by Django 5.1.7 on 2025-04-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ed_platform", "0007_subscriptionmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonmodel",
            name="update",
            field=models.DateTimeField(auto_now=True, verbose_name="Время изменнения"),
        ),
    ]
